apiVersion: v1
kind: Service
metadata:
  name: sample-papi
  labels:
    app: sample-papi
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: bookshelf
    tier: frontend